//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpWoW.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpWoW.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Light.
        /// </summary>
        internal static string AddLight {
            get {
                return ResourceManager.GetString("AddLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border.
        /// </summary>
        internal static string Border {
            get {
                return ResourceManager.GetString("Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush.
        /// </summary>
        internal static string Brush {
            get {
                return ResourceManager.GetString("Brush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush radius:.
        /// </summary>
        internal static string BrushRadius {
            get {
                return ResourceManager.GetString("BrushRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera sensitivity:.
        /// </summary>
        internal static string CameraSensitivity {
            get {
                return ResourceManager.GetString("CameraSensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        internal static string Circle {
            get {
                return ResourceManager.GetString("Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore flag (hex):.
        /// </summary>
        internal static string ExploreFlag {
            get {
                return ResourceManager.GetString("ExploreFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics.
        /// </summary>
        internal static string Graphics {
            get {
                return ResourceManager.GetString("Graphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load current.
        /// </summary>
        internal static string LoadCurrent {
            get {
                return ResourceManager.GetString("LoadCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent ID:.
        /// </summary>
        internal static string ParentID {
            get {
                return ResourceManager.GetString("ParentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save DBC.
        /// </summary>
        internal static string SaveDBC {
            get {
                return ResourceManager.GetString("SaveDBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Entry.
        /// </summary>
        internal static string SaveEntry {
            get {
                return ResourceManager.GetString("SaveEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save folder:.
        /// </summary>
        internal static string SavePath {
            get {
                return ResourceManager.GetString("SavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        internal static string Special {
            get {
                return ResourceManager.GetString("Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the format you like to use for the depth and stencil buffer. The parameters are the following:
        ///D stands for depth and S stands for stencil, X means unused. Ideal is D24S8 which means 24 bits for depth and 8 bits for stencil. You can select the highest possible value, the lockable attribute is optional and you can ignore it..
        /// </summary>
        internal static string StencilExplanation {
            get {
                return ResourceManager.GetString("StencilExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worldmap.
        /// </summary>
        internal static string Worldmap {
            get {
                return ResourceManager.GetString("Worldmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!! WARNING: ADT are not correctly loaded in this mode !!!.
        /// </summary>
        internal static string WorldMapMinimapWarning {
            get {
                return ResourceManager.GetString("WorldMapMinimapWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WoW folder (effects on next start):.
        /// </summary>
        internal static string WoWFolder {
            get {
                return ResourceManager.GetString("WoWFolder", resourceCulture);
            }
        }
    }
}
